apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  labels:
    app: zookeeper-svc
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    protocol: TCP
    targetPort: 2181
    name: porta1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: jplock/zookeeper
        ports:
        - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka-svc
spec:
  selector:
    app: kafka
  type: NodePort
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 30092
    name: porta1
  - port: 7203
    protocol: TCP
    targetPort: 7203
    nodePort: 30093
    name: porta2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: ches/kafka:latest
        ports:
        - containerPort: 9092
        - containerPort: 7203
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-svc"
        - name: ZOOKEEPER_IP
          value: "zookeeper-svc"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        #command: ["sh"]
        #args: ["-c", "unset JMX_PORT;/kafka/bin/kafka-topics.sh --create --zookeeper zookeeper-svc:2181 --replication-factor 1 --partitions 1 --topic simulacao"]
